# Usamos una imagen base de Python
FROM python:3.8-slim

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos el script dentro del contenedor
COPY script.py /app/script.py

# Ejecutamos el script cuando se inicie el contenedor
CMD ["python", "script.py"]
